# coding: UTF-8 -*-
import os.path

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

emoticons = {
    "O:)": "angel",
    "o:)": "angel",
    "O:-)": "angel",
    "o:-)": "angel",
    "o:-3": "angel",
    "o:3": "angel",
    "O;^)": "angel",
    ">:[": "annoyed/disappointed",
    ":-(": "annoyed/disappointed",
    ":(": "annoyed/disappointed",
    ":((": "annoyed/disappointed",
    ":-((": "annoyed/disappointed",
    ":-c": "annoyed/disappointed",
    ":-<": "annoyed/disappointed",
    ":?C": "annoyed/disappointed",
    ":<": "annoyed/disappointed",
    ":[": "annoyed/disappointed",
    ":{": "annoyed/disappointed",
    ":=||": "annoyed/disappointed",
    ":@": "annoyed/disappointed",
    ">:(": "annoyed/disappointed",
    ":/": "annoyed/disappointed",
    ":\\": "annoyed/disappointed",
    "=/": "annoyed/disappointed",
    "=\\": "annoyed/disappointed",
    ">:/": "annoyed/disappointed",
    ">:\\": "annoyed/disappointed",
    ":S": "annoyed/disappointed",
    ":s": "annoyed/disappointed",
    ":-S": "annoyed/disappointed",
    ":-s": "annoyed/disappointed",
    ":|": "annoyed/disappointed",
    ":-|": "annoyed/disappointed",
    ":$": "annoyed/disappointed",
    "?_?": "annoyed/disappointed",
    "(>_<)": "annoyed/disappointed",
    ">_<": "annoyed/disappointed",
    ">__<": "annoyed/disappointed",
    "(>__<)": "annoyed/disappointed",
    "(-.-)": "annoyed/disappointed",
    "(-_-)": "annoyed/disappointed",
    "(._.)": "annoyed/disappointed",
    "/:)": "annoyed/disappointed",
    ":-$": "annoyed/disappointed",
    ">:P": "annoyed/disappointed",
    "K": "annoyed/disappointed",
    "3:)": "devilish",
    "3:-)": "devilish",
    "}:-)": "devilish",
    "}:)": "devilish",
    ">:)": "devilish",
    "B-)": "happy",
    ":-)": "happy",
    ":)": "happy",
    ":o)": "happy",
    ":]": "happy",
    ":3": "happy",
    ":c)": "happy",
    ":>": "happy",
    "=]": "happy",
    "8)": "happy",
    "=)": "happy",
    ":}": "happy",
    ":^)": "happy",
    ":?)": "happy",
    ":-))": "happy",
    "<:-P": "happy",
    "<:P": "happy",
    "<:-p": "happy",
    "<:p": "happy",
    ";;)": "happy",
    "J": "happy",
    "<3": "heart",
    "^5": "high-five",
    ">_>^": "high-five",
    "^<_<": "high-five",
    ":*": "kiss",
    ":*)": "kiss",
    ":^*": "kiss",
    "}{": "kiss",
    "('}{')": "kiss",
    ":-D": "laughing",
    ":D": "laughing",
    "8-D": "laughing",
    "8D": "laughing",
    "x-D": "laughing",
    "xD": "laughing",
    "X-D": "laughing",
    "XD": "laughing",
    "=-D": "laughing",
    "=D": "laughing",
    ";D": "laughing",
    "-3": "laughing",
    "3": "laughing",
    "B^D": "laughing",
    "D:<": "laughing",
    "D:": "laughing",
    "D8": "laughing",
    "D;": "laughing",
    "D=": "laughing",
    "DX": "laughing",
    ":-B": "nerd",
    "8-)": "nerd",
    "8)": "nerd",
    "</3": "sad",
    ":'(": "sad",
    ":'-(": "sad",
    "QQ": "sad",
    "L": "sad",
    ":#": "sealed mouth",
    ":-#": "sealed mouth",
    ":-X": "sealed mouth",
    ":-x": "sealed mouth",
    ":X": "sealed mouth",
    ":x": "sealed mouth",
    "??": "shooting star",
    "??": "shooting star",
    "~?": "shooting star",
    ">:O": "suprprised/shocked",
    ">:o": "suprprised/shocked",
    ":-O": "suprprised/shocked",
    ":-o": "suprprised/shocked",
    ":O": "suprprised/shocked",
    ":o": "suprprised/shocked",
    "O_o": "suprprised/shocked",
    "o_O": "suprprised/shocked",
    "O.o": "suprprised/shocked",
    "o.O": "suprprised/shocked",
    "(O_o)": "suprprised/shocked",
    "(o_O)": "suprprised/shocked",
    "(O.o)": "suprprised/shocked",
    "(o.O)": "suprprised/shocked",
    ":'-)": "tears of happines",
    ":')": "tears of happines",
    ":P": "teasing/playful",
    ":p": "teasing/playful",
    ">:P": "teasing/playful",
    ">:p": "teasing/playful",
    "X-P": "teasing/playful",
    "x-p": "teasing/playful",
    "xp": "teasing/playful",
    "XP": "teasing/playful",
    ":-P": "teasing/playful",
    ":-p": "teasing/playful",
    "=P": "teasing/playful",
    "=P": "teasing/playful",
    ":-?": "teasing/playful",
    ":-b": "teasing/playful",
    ":b": "teasing/playful",
    ";)": "wink",
    u"º)": "wink",
    ";-)": "wink",
    ";]": "wink",
    u"^Ü^": "happy",
}

special_tokens = emoticons
